services:
  - type: web
    name: badier-ride-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/badier-ride-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://badier_ride_db_user:wS2EiwS2mLCTZlKhaDJtwm3wLccxVZHR@dpg-d19b1mbuibrs73c26m1g-a.oregon-postgres.render.com/badier_ride_db
      - key: SPRING_DATASOURCE_USERNAME
        value: badier_ride_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: wS2EiwS2mLCTZlKhaDJtwm3wLccxVZHR
      - key: JWT_SECRET
        value: fcwzgf89pZlOuhZ8sKDejXIM5Bq02IsQUX+WWheNmz8=
      - key: MAPS_API_KEY
        value: AIzaSyBafTaXaUdnQbnRNysnBfG7H8Vql5VzOOI
